In [2]:
import pandas as pd
import numpy as np

In [78]:

import os
print(os.getcwd())


c:\Users\mohak\OneDrive\Documents\GitHub\Apple-Sales-SQL-Analysis\Notebooks\Numpy\Notebooks


In [ ]:

 'Q1: Load the sales dataset using Pandas and convert the 'quantity' column into a NumPy array.'

In [80]:
sales = pd.read_csv("../../../Data/sales.csv")

In [61]:
sales["quantity"].to_numpy()

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [ ]:
' Q2: Explore the NumPy array by checking its shape, size, dimensions, and data type.'

In [ ]:



print(sales.columns)

Index(['sale_id', 'sale_date', 'store_id', 'product_id', 'quantity'], dtype='object')


In [ ]:
print(quantity[:10])

[1 1 1 1 1 1 1 1 1 1]


In [ ]:
print(type(quantity))

<class 'numpy.ndarray'>


In [ ]:
print(quantity.shape)

(1040191,)


In [ ]:

quantity.dtype

dtype('int64')

In [ ]:
quantity.ndim

1

In [ ]:
quantity.size

1040191

In [74]:
'Q3: Convert the data type of the quantity array from integer to float using astype().'

'Q3: Convert the data type of the quantity array from integer to float using astype().'

In [65]:
sales["quantity"].dtype   

dtype('int64')

In [42]:
quantity.astype(float)

array([1., 1., 1., ..., 1., 1., 1.])

In [73]:
' Q5: Create a 2D NumPy matrix by combining Sale ID, Store ID, Product ID, and Quantity into columns using np.column_stack().'

' Q5: Create a 2D NumPy matrix by combining Sale ID, Store ID, Product ID, and Quantity into columns using np.column_stack().'

In [66]:
np.zeros(quantity.shape)

array([0., 0., 0., ..., 0., 0., 0.])

In [67]:
np.ones(quantity.shape)

array([1., 1., 1., ..., 1., 1., 1.])

In [ ]:

np.full(quantity.shape, 7)

array([7, 7, 7, ..., 7, 7, 7])

In [75]:
' Q5: Create a 2D NumPy matrix by combining Sale ID, Store ID, Product ID, and Quantity into columns using np.column_stack().'

' Q5: Create a 2D NumPy matrix by combining Sale ID, Store ID, Product ID, and Quantity into columns using np.column_stack().'

In [58]:
matrix = sales.to_numpy()

In [59]:
matrix.shape

(1040191, 5)

In [ ]:
'if you have to create a matrix from individual arrays, you can use the following code:'

'if you have to create a matrix from individual arrays, you can use the following code:'

In [76]:
sale_id = sales["sale_id"].to_numpy()
store_id = sales["store_id"].to_numpy()
product_id = sales["product_id"].to_numpy()
quantity = sales["quantity"].to_numpy()

In [77]:
matrix = np.column_stack((sale_id, store_id, product_id, quantity))