In [13]:
import pandas as pd
import numpy as np

In [14]:
sales = pd.read_csv("../../../Data/sales.csv")

In [15]:

# Q1: Access individual elements of a NumPy array using positive and negative indexing.

In [24]:
quantity = sales['quantity'].to_numpy()

In [26]:
print(quantity[0])
print(quantity[1])
print(quantity[-1])
print(quantity[-2])

1
1
1
1


In [27]:
# Q2: Extract multiple elements from a NumPy array using slicing.

In [30]:
# first 5 elements
print(quantity[:5])

# last 5 elements
print(quantity[-5:])

# between index 10 and 20
print(quantity[10:21])

[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1]


In [38]:
# Q3: Reverse the order of elements in a NumPy array.

In [39]:
# Full reverse
print(quantity[::-1])

# Reverse and extract the last three elements
print(quantity[-1:-4:-1])

[1 1 1 ... 1 1 1]
[1 1 1]


In [40]:
# Q4: Access rows and columns from a 2D NumPy array using indexing.

In [42]:
matrix = sales.to_numpy()
matrix.shape

(1040191, 5)

In [ ]:

# Q4: 2D Array Slicing
# Practice slicing on the 2D array `matrix` to access specific rows and columns.

In [ ]:


# Q4.1 Display the first 5 rows and all columns.
print(matrix[:5, :])

# Q4.2 Display all rows and the first 3 columns.
print(matrix[:, :3])

# Q4.3 Display the first 10 rows and the first 2 columns.
print(matrix[:10, :2])

# Q4.4 Display the last 5 rows and the last 2 columns.
print(matrix[-5:, -2:])

# Q4.5 Display rows 10 to 19 and columns 1 to 2.
print(matrix[10:20, 1:3])

# Q4.6 Display every second row and all columns.
print(matrix[::2, :])

# Q4.7 Display all rows with columns in reverse order.
print(matrix[:, ::-1])

# Q4.8 Display the first 5 rows with columns in reverse order.
print(matrix[:5, ::-1]) 

# Q4.9 Display the last 10 rows and the first 2 columns.
print(matrix[-10  :, :2])

# Q4.10 Display every second row and every second column.
print(matrix[::2, ::2])

[['OID-358365' '2021-09-16' 'ST-33' 'P-44' 1]
 ['OID-358510' '2022-01-28' 'ST-33' 'P-44' 1]
 ['OID-358525' '2021-11-26' 'ST-33' 'P-44' 1]
 ['OID-358591' '2021-09-15' 'ST-33' 'P-44' 1]
 ['OID-358601' '2022-02-07' 'ST-33' 'P-44' 1]]
[['OID-358365' '2021-09-16' 'ST-33']
 ['OID-358510' '2022-01-28' 'ST-33']
 ['OID-358525' '2021-11-26' 'ST-33']
 ...
 ['OID-358353' '2022-05-27' 'ST-33']
 ['OID-358354' '2022-03-22' 'ST-33']
 ['OID-358355' '2022-07-19' 'ST-33']]
[['OID-358365' '2021-09-16']
 ['OID-358510' '2022-01-28']
 ['OID-358525' '2021-11-26']
 ['OID-358591' '2021-09-15']
 ['OID-358601' '2022-02-07']
 ['OID-358877' '2022-03-10']
 ['OID-358995' '2022-04-05']
 ['OID-358996' '2021-11-22']
 ['OID-359012' '2022-03-28']
 ['OID-359013' '2022-02-08']]
[['P-48' 1]
 ['P-49' 1]
 ['P-49' 1]
 ['P-49' 1]
 ['P-49' 1]]
[['2021-09-20' 'ST-33']
 ['2022-04-02' 'ST-33']
 ['2022-03-08' 'ST-33']
 ['2021-09-06' 'ST-33']
 ['2022-01-19' 'ST-33']
 ['2022-03-23' 'ST-33']
 ['2022-03-10' 'ST-33']
 ['2021-11-04' 'ST-33

In [49]:
# Q4 Display the middle 20 Quantity values. (Main Question)

In [46]:
middle = len(quantity) // 2
print(quantity[middle-10 : middle+10])

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
