In [87]:
import pandas as pd
import numpy as np

In [88]:
sales = pd.read_csv("../../../Data/sales.csv")
quantity = sales["quantity"].to_numpy()
matrix = sales.to_numpy()

In [89]:
# Q.1 Take the first 100 Quantity values and reshape them into a 10 × 10 matrix.

In [90]:
quantity_matrix = quantity[:100].reshape(10, 10)

In [91]:
print(quantity_matrix)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [92]:
# Q.2 Flatten the reshaped matrix back into a 1D array.

In [93]:
quantity_flattened = quantity_matrix.flatten()
print(quantity_flattened)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [94]:
# Q3: Horizontally stack Product ID and Quantity

In [95]:
product_2D = sales["product_id"].to_numpy().reshape(-1,1)
quantity_2D = sales["quantity"].to_numpy().reshape(-1,1)

In [100]:
stacked_matrix =np.hstack((product_2D, quantity_2D))
print(stacked_matrix)

[['P-44' 1]
 ['P-44' 1]
 ['P-44' 1]
 ...
 ['P-49' 1]
 ['P-49' 1]
 ['P-49' 1]]


In [97]:
# Q4: Vertically stack two equal-sized Quantity arrays

In [101]:
q1 = quantity[:50]
q2 = quantity[50:100]

In [102]:
stacked_quantity = np.vstack((q1, q2))
print(stacked_quantity.shape)

(2, 50)


In [111]:
# Q5: Split the first 1000 Quantity values into 10 equal-sized batches.

In [104]:
batches = np.split(quantity[:1000],10)


In [109]:
print(len(batches))

10


In [110]:
print(batches[0].shape)

(100,)
