In [31]:
import numpy as np 
import pandas as pd

In [32]:
sales = pd.read_csv("../../../Data/sales.csv")

In [33]:
quantity = sales['quantity'].to_numpy()

In [34]:
# Increase every Quantity value by 1.

In [35]:
quantity[:10] + 1

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [36]:
# Multiply every Quantity value by 2.

In [37]:
quantity[:10] * 2

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [38]:
# Simulate a festival sale by adding 10 bonus units to every sale using vectorized operations

In [39]:
festival_quantity = quantity + 10

print(festival_quantity)

[11 11 11 ... 11 11 11]


In [40]:
# Create a promotional multiplier array and apply it using broadcasting

In [41]:
multiplier = np.full(quantity.shape, 1.1)

In [42]:
prom = quantity * multiplier

In [43]:
print(prom[:10])

[1.1 1.1 1.1 1.1 1.1 1.1 1.1 1.1 1.1 1.1]


In [44]:
# Simulate different stock replenishment values for different stores using broadcasting without writing loops.

In [45]:
store_id = sales["store_id"].to_numpy()


In [46]:
stock = np.array([100, 200, 300, 400, 500])

In [49]:
new_quantity = quantity[:5] + stock

In [52]:
print(new_quantity[:3])

[101 201 301]
