In [1]:
import numpy as np 
import pandas as pd

In [2]:
sales = pd.read_csv("../../../Data/sales.csv")

In [4]:
quantity = np.array(sales['quantity'])

In [7]:
# Calculate the total quantity sold using np.sum()

In [6]:
print(np.sum(quantity))

1188103


In [8]:
# Calculate the Average Quantity Sold

In [12]:
print(np.average(quantity))
print(np.mean(quantity))   # Same but np.mean() is more commonly used for calculating the mean of an array.

1.142196961904112
1.142196961904112


In [13]:
# Find the Minimum and Maximum Quantity sold

In [14]:
print(f"Minimum quantity sold: {np.min(quantity)}")
print(f"Maximum quantity sold: {np.max(quantity)}")

Minimum quantity sold: 1
Maximum quantity sold: 6


In [15]:
print(np.min(quantity))
print(np.max(quantity))

1
6


In [16]:
# Using a reshaped Quantity matrix, calculate row-wise and column-wise totals

In [19]:
quantity_matrix = quantity[:100].reshape(10,10)
print(quantity_matrix)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [21]:
row_totals = np.sum(quantity_matrix, axis=1)
col_total = np.sum(quantity_matrix, axis =0)

In [22]:
print(row_totals)
print(col_total)

[10 10 10 10 10 10 10 10 10 10]
[10 10 10 10 10 10 10 10 10 10]


In [23]:
# Build a Sales Summary Report containing Total Quantity, Average Quantity, Maximum Quantity, Minimum Quantity, and explain which KPI would be most useful for a business manager.

In [25]:
print(f"Total Quantity Sold: {np.sum(quantity)}")
print(f"Average Quantity Sold: {np.mean(quantity)}")
print(f"Maximum Quantity Sold: {np.max(quantity)}")
print(f"Minimum Quantity Sold: {np.min(quantity)}")

print("\nMost useful KPI: Average Quantity Sold")
print("Reason: It shows the typical quantity sold per sale.")

Total Quantity Sold: 1188103
Average Quantity Sold: 1.142196961904112
Maximum Quantity Sold: 6
Minimum Quantity Sold: 1

Most useful KPI: Average Quantity Sold
Reason: It shows the typical quantity sold per sale.
