In [1]:
import pandas as pd
import numpy as np

In [5]:
sales = pd.read_csv("../../../Data/Sales.csv")

In [7]:
quantity = sales["quantity"].to_numpy()

In [14]:
# Display all sales where the Quantity is greater than 2

In [15]:
quantity > 2

array([False, False, False, ..., False, False, False])

In [16]:
quantity[quantity > 2]

array([3, 3, 3, ..., 3, 3, 3], dtype=int64)

In [17]:
# Display all sales where the Quantity is equal to 1


In [18]:
quantity[quantity == 1]

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [19]:
# Count the total number of sales where the Quantity is greater than the average Quantity

In [22]:
len(quantity[quantity > np.mean(quantity)])

98367

In [43]:
# Replace every Quantity value greater than 4 with 4 using NumPy

In [41]:
replaced_quantity = quantity.copy()

replaced_quantity[replaced_quantity > 4] = 4

print(replaced_quantity)

[1 1 1 ... 1 1 1]


In [ ]:
 
print(np.unique(replaced_quantity))   # After change

[1 2 3 4]


In [45]:
print(np.unique(quantity))   # Before change

[1 2 3 4 5]


In [46]:
# Create a filtered NumPy matrix containing only high-volume sales (Quantity > Average Quantity) and prepare it for further business analysis.

In [47]:
quantity > np.average(quantity)

array([False, False, False, ..., False, False, False])

In [48]:
matrix =sales.to_numpy()

In [49]:
quantity[quantity > np.mean(quantity)]

array([2, 2, 2, ..., 2, 3, 2], dtype=int64)

In [ ]:

matrix[quantity > np.mean(quantity)]


array([['OID-398187', '2019-12-21', 'ST-30', 'P-20', 2],
       ['OID-398189', '2020-04-08', 'ST-30', 'P-21', 2],
       ['OID-398193', '2020-02-01', 'ST-30', 'P-21', 2],
       ...,
       ['OID-1048548', '2019-01-02', 'ST-1', 'P-16', 2],
       ['OID-1048550', '2019-01-02', 'ST-1', 'P-16', 3],
       ['OID-1048551', '2019-01-02', 'ST-1', 'P-16', 2]], dtype=object)

In [55]:
print("Business Insight:")
print("This filtered dataset contains only high-volume sales, helping managers focus on the best-performing transactions for analysis and decision-making.")

Business Insight:
This filtered dataset contains only high-volume sales, helping managers focus on the best-performing transactions for analysis and decision-making.
