In [1]:
import pandas as pd
import numpy as  np 

In [2]:
sales = pd.read_csv("../../../Data/Sales.csv")

In [3]:
quantity = sales[["quantity"]].to_numpy()

In [8]:
# Sort the Quantity array in ascending order

In [6]:
np.sort(quantity)

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [7]:
# Find all unique Quantity values present in the Sales dataset


In [9]:
np.unique(quantity)

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [10]:
# Find all unique Product IDs that appear in the Sales dataset

In [11]:
product_id = sales[["product_id"]].to_numpy()

In [12]:
np.unique(product_id)

array(['P-1', 'P-10', 'P-11', 'P-12', 'P-13', 'P-14', 'P-15', 'P-16',
       'P-17', 'P-18', 'P-19', 'P-2', 'P-20', 'P-21', 'P-22', 'P-23',
       'P-24', 'P-25', 'P-26', 'P-27', 'P-28', 'P-29', 'P-3', 'P-30',
       'P-31', 'P-32', 'P-33', 'P-34', 'P-35', 'P-36', 'P-37', 'P-38',
       'P-39', 'P-4', 'P-40', 'P-41', 'P-42', 'P-43', 'P-44', 'P-45',
       'P-46', 'P-47', 'P-48', 'P-49', 'P-5', 'P-50', 'P-51', 'P-52',
       'P-53', 'P-54', 'P-55', 'P-56', 'P-57', 'P-58', 'P-59', 'P-6',
       'P-60', 'P-61', 'P-62', 'P-63', 'P-64', 'P-7', 'P-8', 'P-9'],
      dtype=object)

In [16]:
np.unique(quantity, return_counts = True)

(array([1, 2, 3, 4, 5, 6], dtype=int64),
 array([941824,  49249,  48907,     71,     64,     76], dtype=int64))

In [17]:
# Rank all sales based on Quantity using argsort() without modifying the original dataset and identify the Top 20 highest quantity sales

In [21]:
rank = np.argsort(quantity)

In [32]:
top_20_indexes = rank[-20:][::-1]    # We can use the negative indexing to get the last 20 elements and then reverse the order to get the top 20 highest quantity sales

In [33]:
top_20_quantity = quantity[top_20_indexes]

In [34]:
print("Top 20 highest quantity sales are: ", top_20_quantity)

Top 20 highest quantity sales are:  [[[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]]


In [35]:
print("Business Insight:")
print("Top 20 highest quantity sales help identify the best-performing transactions for inventory planning and sales analysis.")

Business Insight:
Top 20 highest quantity sales help identify the best-performing transactions for inventory planning and sales analysis.
