In [3]:
import pandas as pd 
import numpy as np 


In [4]:
sales = pd.read_csv("../../../Data/Sales.csv")

In [5]:
quantity = sales['quantity'].to_numpy()

In [6]:
# Calculate the Mean Quantity sold.

In [7]:
np.mean(quantity)

1.142196961904112

In [8]:
# Calculate the Median Quantity sold.

In [9]:
np.median(quantity)

1.0

In [10]:
# Calculate the Variance and Standard Deviation of the Quantity values.

In [11]:
print(np.std(quantity)) # Standard Deviation
print(np.var(quantity)) # Variance

0.46756900601649143
0.2186207753872498


In [12]:
# Calculate the 25th, 50th, and 75th Percentiles of Quantity sold and interpret what they represent.

In [13]:
np.percentile(quantity, 25), np.percentile(quantity, 50), np.percentile(quantity, 75)  # it ha many ways to write this code. You can also write it as below.


(1.0, 1.0, 1.0)

In [14]:
print(np.unique(quantity, return_counts=True))

# The dataset is heavily concentrated around single-unit sales. Since most transactions have a quantity of 1, the 25th, 50th, and 75th percentiles are all 1.

(array([1, 2, 3, 4, 5, 6], dtype=int64), array([941824,  49249,  48907,     71,     64,     76], dtype=int64))


In [15]:
# Normalize the Quantity values between 0 and 1 and identify potential outliers using statistical measures .

In [16]:
normalized_quantity = (quantity - np.min(quantity)) / (np.max(quantity) - np.min(quantity))

In [17]:
print(normalized_quantity[-20:])

# Business Insight:
# Normalization removes the effect of different value scales, allowing fair comparison
# between sales records and improving the accuracy of further analysis.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
print(np.min(quantity))
print(np.max(quantity))

1
6


In [19]:
str = np.std(quantity)
mean = np.mean(quantity)

In [20]:
lower_limit = mean - 3 * str
upper_limit = mean + 3 * str 

In [21]:
print(lower_limit, upper_limit)

-0.2605100561453624 2.5449039799535864


In [22]:
outliers = quantity[(quantity < lower_limit) | (quantity > upper_limit)]

In [23]:
print(outliers)


[3 3 3 ... 3 3 3]


In [24]:
# Business Insight:
# Potential outliers were identified using the Mean ± 3×Standard Deviation rule.
# These values should be reviewed as they may represent unusual sales or bulk purchases.